[workspace]
members = ["sleef-trig", "sleef-trig-sys"]

[profile.release]
opt-level = 3
lto = "thin"
debug = true
codegen-units = 1

[profile.bench]
opt-level = 3
lto = "thin"
debug = false
codegen-units = 1

[profile.test]
opt-level = 3
lto = "thin"
debug = false
