name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install latest Rust (nightly)
      uses: actions-rs/toolchain@v1
      with:
          profile: minimal
          toolchain: nightly
          override: true
    - name: Run tests
      run: cargo test --workspace --verbose

  test:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install latest Rust (stable)
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Build
      run: cargo build --release -p sleef-trig

